# prometheus/prometheus.yml
global:
  scrape_interval: 5s # Raspa métricas a cada 5 segundos
  external_labels:
    monitor: 'microservices-monitor'

scrape_configs:
  - job_name: 'api-gateway'
    # O target é o nome do container do Docker Compose e a porta onde ele expõe as métricas
    static_configs:
      - targets: ['api_gateway_service:3000']
    metrics_path: /metrics # O endpoint que você adicionou em cada serviço

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth_service:3001']
    metrics_path: /metrics

  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:3002']
    metrics_path: /metrics

  - job_name: 'agenda-service'
    static_configs:
      - targets: ['agenda_service:3003']
    metrics_path: /metrics