openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
  description: Documentação da API do serviço de Autenticação.
servers:
  - url: http://localhost:3001/api
    description: Servidor de Desenvolvimento
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths: {}
tags: []
